<a href="https://colab.research.google.com/github/q890003/ML_Naive-Bayes-Classifier/blob/master/ML_HW2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import sys
import dill
import numpy as np
import math
from itertools import product 
from struct import unpack 


def get_img(img_file_path):
    with open(img_file_path, "rb") as img_file:
        magic, num_imgs, rows, cols = unpack(">IIII", img_file.read(16))

        imgs_mtx = np.zeros((num_imgs, rows, cols), dtype=int)
        for img in range(num_imgs):
            for (row, col) in product(range(rows), range(cols)):
                tmp = unpack(">B", img_file.read(1))
                tmp = int(str(tmp[0]))
                imgs_mtx[img][row,col] = tmp
    return imgs_mtx, num_imgs

def get_label(lbl_file_path):
    with open(lbl_file_path, "rb") as label_file:
        magic, num_itms = unpack(">II", label_file.read(8))
        lbls_mtx = np.zeros((num_itms), dtype=int)
        for img in range(num_itms):
            label = unpack(">B", label_file.read(1))
            label = int(str(label[0]))
            lbls_mtx[img] = label
    return lbls_mtx


label_types = 10
gray_bins = 32
#mode = int(sys.argv[1])  #mode = 0 -> Discrete; mode = 1 -> Contineous
mode = 0    # for test
rows = 28
cols = 28

train_img_pth = "/content/drive/My Drive/Colab Notebooks/ML_hw2_data/train-images.idx3-ubyte"
train_label_pth = "/content/drive/My Drive/Colab Notebooks/ML_hw2_data/train-labels.idx1-ubyte"
train_img_mtx, train_num_imgs = get_img(train_img_pth)
train_label_mtx = get_label(train_label_pth)

test_img_pth = "/content/drive/My Drive/Colab Notebooks/ML_hw2_data/t10k-images.idx3-ubyte"
test_label_pth = "/content/drive/My Drive/Colab Notebooks/ML_hw2_data/t10k-labels.idx1-ubyte"
test_img_mtx, tests_num_imgs = get_img(test_img_pth)
test_label_mtx = get_label(test_label_pth)
#dill.dump_session('ML_HW2_env.db')

In [0]:
if mode == 0:
    #training 
    labels_count = np.zeros((label_types), dtype=float)
    likelyhood = np.zeros((label_types,rows,cols,gray_bins), dtype=float)
    for img in range(train_num_imgs):
        lbl = train_label_mtx[img]
        labels_count[lbl] += 1
        for (row, col) in product(range(rows), range(cols)):
            gray = train_img_mtx[img][row, col] // 8
            likelyhood[lbl][row,col,gray] += 1
    prior = labels_count/train_num_imgs

In [0]:
# dill.load_session('ML_HW2_env.db')
#testing
error_rate = 0 
for img in range(tests_num_imgs):
    posterior = np.zeros((label_types), dtype=float)
    true_label = test_label_mtx[img]
    likeli_cnt = 0
    for (row, col) in product(range(rows), range(cols)):
        gray = test_img_mtx[img][row, col] //8

        for label in range(label_types):
            if likelyhood[label][row,col,gray] > 0: 
                likeli_cnt += 1
                posterior[label] += math.log10(likelyhood[label][row,col,gray])
    for label in range(label_types):
        posterior[label] -= math.log10(labels_count[label])*784
        posterior[label] += math.log10(prior[label])
    normalization = np.sum(posterior)
    posterior /= normalization
    
    # print("Postirior (in log scale):")
    # for i in range(label_types):
    #     print('{label}: {posterior}'.format(label=i, posterior=posterior[i]))
    # print('Prediction: {prediction}, Ans: {ans}'.format(prediction=np.argmin(posterior), ans= true_label))
    if np.argmin(posterior) != true_label:
        error_rate += 1

error_rate /= tests_num_imgs
print(error_rate)

0.1532


In [0]:
#dill.load_session('ML_HW2_env.db')

pixels_mean = np.zeros((label_types, rows, cols), dtype =float)
pixels_var = np.zeros((label_types, rows, cols), dtype = float)
labels_count = np.zeros((label_types), dtype=int)

#pixels mean in each label
pixels_tmp = np.zeros((label_types, rows, cols), dtype = float)
for img in range(train_num_imgs):
    lbl = train_label_mtx[img]
    labels_count[lbl] += 1
    pixels_tmp[lbl] += train_img_mtx[img]
for label in range(label_types):
    pixels_mean[label] = pixels_tmp[label] / labels_count[label]

#pixels var in each pixel of each label
for img in range(train_num_imgs):
    lbl = train_label_mtx[img] 
    pixels_var[lbl] += np.square(train_img_mtx[img] - pixels_mean[lbl]) 
for label in range(label_types):
    pixels_var[label] = pixels_var[label] / labels_count[label]

#label mean and var
label_mean = np.mean(labels_count)   
label_var = np.var(labels_count)

In [0]:
pixels_mean


In [0]:
log_two_pi = math.log(2*3.1415926)
error_rate = 0
t = 0 
for img in range(tests_num_imgs):
    posterior = np.zeros((label_types), dtype=float)
    for label in range(label_types):
        posterior[label] += -0.5* (log_two_pi+ math.log10(label_var)+(label - label_mean)**2/label_var)
        for (row, col) in product(range(rows), range(cols)):
                pixel = test_img_mtx[img][row,col]
                if pixels_var[label][row,col] > 0:
                    pxl_mean = pixels_mean[label][row,col]
                    pxl_var = pixels_var[label][row,col]
                    posterior[label] += -0.5* (log_two_pi+ math.log10(pxl_var)+ (pixel- pxl_mean)**2/pxl_var)

    normalization = np.sum(posterior)
    posterior /= normalization

    true_label = test_label_mtx[img]
    # print("Postirior (in log scale):")
    # for label in range(label_types):
    #     print('{label}: {posterior}'.format(label=label, posterior=posterior[label]))
    # print('Prediction: {prediction}, ans: {ans}'.format(prediction=np.argmin(posterior), ans= true_label))
    if np.argmin(posterior) != true_label:
        error_rate += 1
    t +=1
    if t> 100:
        print(error_rate)
        break

#imagination number
print("Imagination of numbers in Bayesian classifier:")
for label in range(label_types):
    imagination = np.zeros((rows, cols), dtype=int)
    for (row, col) in product(range(rows), range(cols)):
        if pixels_mean[label][row, col] > 60:
            imagination[row,col] = 1

    print("{label}: ".format(label=label))
    print(imagination)
error_rate /= tests_num_imgs
print("Error_rate", error_rate)

24
Imagination of numbers in Bayesian classifier:
0: 
[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 0 0 0 0]
 [0 0 0 0 0 0 0 1 1 1 1 1 1 1 0 0 0 0 1 1 1 1 1 1 0 0 0 0]
 [0 0 0 0 0 0 1 1 1 1 1 1 1 0 0 0 0 0 0 1 1 1 1 1 0 0 0 0]
 [0 0 0 0 0 0 1 1 1 1 1 1 0 0 0 0 0 0 0 1 1 1 1 1 0 0 0 0]
 [0 0 0 0 0 0 1 1 1 1 1 0 0 0 0 0 0 0 0 1 1 1 1 1 0 0 0 0]
 [0 0 0 0 0 1 1 1 1 1 1 0 0 0 0 0 0 0 1 1 1 1 1 1 0 0 0 0]
 [

In [0]:
pixel_meanq = np.zeros((10,28,28), dtype = float)
pixel_varq = np.zeros((10,28,28), dtype = float)
label_num = np.zeros(10,dtype = int)
train_img_arr = train_img_mtx / 256
test_img_arr = test_img_mtx / 256
error = 0
for i in range(60000):
    label = train_label_mtx[i]
    label_num[label] += 1
    pixel_meanq[label] += train_img_arr[i]
for i in range(10):# mean
    pixel_meanq[i] = pixel_meanq[i] / label_num[i]
for i in range(60000):
    label = train_label_mtx[i]
    tmp = train_img_arr[i] - pixel_meanq[label]
    pixel_varq[label] += np.square(tmp)
for i in range(10):#variance
    pixel_varq[i] = pixel_varq[i] / label_num[i]

constant = math.log(2*3.1415926)

for i in range(10000):
    posterior = np.zeros(10,dtype = float)
    total = 0.0
    for j in range(10):
        posterior[j] += -0.5*(constant+math.log(label_var)+(j-label_mean)*(j-label_mean)/label_var)
        for x in range(28):
            for y in range(28):
                var = pixel_varq[j][x][y]
                if var > 0:
                    posterior[j] += -0.5*(constant+math.log(var)+(test_img_arr[i][x][y]-pixel_meanq[j][x][y])**2/var)   
                    
        total += posterior[j]
    # print('Posterior (in log scale):')
    # for j in range(10):
    #     posterior[j]/=total
    #     print(j,': ',posterior[j])
    # print('Prediction: ',np.argmin(posterior),', Ans: ',test_label_mtx[i])
    if np.argmin(posterior) != test_label_mtx[i]:
        error += 1
    # if i >100:
    #     break
for i in range(10):
    print(i,': ')
    for x in range(28):
        for y in range(28):
            if pixel_meanq[i][x][y] > 0.5:
                print(1,end=' ')
            else :
                print(0,end=' ')
        print(' ')
    print(' ')
print('Error rate: ',error/10000)

0 : 
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0  
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0  
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0  
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0  
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0  
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0  
0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0  
0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0  
0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0  
0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 0 0 0 1 1 1 1 0 0 0 0 0 0  
0 0 0 0 0 0 0 0 0 1 1 1 1 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0  
0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0  
0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0  
0 0 0 0 0 0 0 1 1 1 1 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0  
0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0  
0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0  
0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0  
0 0 0 0 0